alter table sys_tenant_db modify id int auto_increment;
ALTER TABLE sys_tenant_resource DROP COLUMN resource_new_id;
ALTER TABLE sys_tenant_resource ADD `resource_original_id` int(20) COMMENT '对应master中的资源主键';
ALTER TABLE sys_logininfor ADD `tenant_key` varchar(100) DEFAULT 'master' COMMENT '租户标识';
ALTER TABLE sys_notice ADD `tenant_key` varchar(100) DEFAULT 'master' NOT NULL COMMENT '租户标识';
ALTER TABLE sys_tenant_db ADD `del_flag` char(1) DEFAULT '0' COMMENT '删除标志（0代表存在 1代表删除）';
ALTER TABLE sys_role_dept ADD `tenant_key` varchar(100) DEFAULT 'master' COMMENT '租户标识';
ALTER TABLE sys_role_menu ADD `tenant_key` varchar(100) DEFAULT 'master' COMMENT '租户标识';
ALTER TABLE sys_user_part_dept ADD `tenant_key` varchar(100) DEFAULT 'master' COMMENT '租户标识';
ALTER TABLE sys_user_post ADD `tenant_key` varchar(100) DEFAULT 'master' COMMENT '租户标识';
ALTER TABLE sys_user_role ADD `tenant_key` varchar(100) DEFAULT 'master' COMMENT '租户标识';
ALTER TABLE `sys_role_dept` DROP PRIMARY KEY ,ADD PRIMARY KEY ( `role_id`,`dept_id`,`tenant_key` );
ALTER TABLE `sys_role_menu` DROP PRIMARY KEY ,ADD PRIMARY KEY ( `role_id`,`menu_id`,`tenant_key` );
ALTER TABLE `sys_user_part_dept` DROP PRIMARY KEY ,ADD PRIMARY KEY ( `user_id`,`dept_id`,`tenant_key` );
ALTER TABLE `sys_user_post` DROP PRIMARY KEY ,ADD PRIMARY KEY ( `user_id`,`post_id`,`tenant_key` );
ALTER TABLE `sys_user_role` DROP PRIMARY KEY ,ADD PRIMARY KEY ( `user_id`,`role_id`,`tenant_key` );
ALTER TABLE sys_dept MODIFY COLUMN `tenant_key` varchar(100) DEFAULT 'master' NOT NULL COMMENT '租户标识';
ALTER TABLE sys_menu MODIFY COLUMN `tenant_key` varchar(100) DEFAULT 'master' NOT NULL COMMENT '租户标识';
ALTER TABLE sys_notice MODIFY COLUMN `tenant_key` varchar(100) DEFAULT 'master' NOT NULL COMMENT '租户标识';
ALTER TABLE sys_oper_log MODIFY COLUMN `tenant_key` varchar(100) DEFAULT 'master' NOT NULL COMMENT '租户标识';
ALTER TABLE sys_post MODIFY COLUMN `tenant_key` varchar(100) DEFAULT 'master' NOT NULL COMMENT '租户标识';
ALTER TABLE sys_role MODIFY COLUMN `tenant_key` varchar(100) DEFAULT 'master' NOT NULL COMMENT '租户标识';
ALTER TABLE sys_user MODIFY COLUMN `tenant_key` varchar(100) DEFAULT 'master' NOT NULL COMMENT '租户标识';
ALTER TABLE sys_dept ADD `dept_type` varchar(1) COMMENT '部门类型(存放字典项dept_type的值)';
ALTER TABLE sys_tenant_resource ADD `misty_flag` varchar(1) DEFAULT '0' COMMENT '用于树形控件的层级独立或者层级关联，半选状态(0：自身被选中  1：自身未被选中，选中的是子集菜单)';