CREATE TABLE `sys_general_log` (
  `log_id` int(20) NOT NULL AUTO_INCREMENT COMMENT '日志主键',
  `log_title` varchar(255) DEFAULT NULL COMMENT '日志标题',
  `log_type` int(1) DEFAULT NULL COMMENT '日志类型（0其它 1推送 2接收 3拉取）',
  `trigger_type` int(1) DEFAULT NULL COMMENT '触发类型（0其它 1自动 2手动）',
  `request_method` varchar(10) DEFAULT NULL COMMENT '请求方式',
  `request_url` varchar(100) DEFAULT NULL COMMENT '请求地址',
  `request_param` text COMMENT '请求参数,json格式',
  `request_result` text COMMENT '返回结果,json格式',
  `result_status` int(1) DEFAULT NULL COMMENT '结果状态（1成功 2失败）',
  `operate_user` varchar(64) DEFAULT NULL COMMENT '操作人员',
  `operate_ip` varchar(20) DEFAULT NULL COMMENT '操作地址',
  `operate_location` varchar(100) DEFAULT NULL COMMENT '操作地点',
  `error_msg` text COMMENT '错误消息',
  `trigger_time` datetime DEFAULT NULL COMMENT '触发时间',
  `create_user` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_user` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `tenant_key` varchar(100) DEFAULT NULL COMMENT '租户标识',
  `var1` varchar(255) DEFAULT NULL COMMENT '备用字段1',
  `var2` varchar(255) DEFAULT NULL COMMENT '备用字段2',
  `var3` varchar(255) DEFAULT NULL COMMENT '备用字段3',
  `var4` varchar(255) DEFAULT NULL COMMENT '备用字段4',
  `var5` varchar(255) DEFAULT NULL COMMENT '备用字段5',
  PRIMARY KEY (`log_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;